/** Deterministic action body used only by acceptance infrastructure. */
export const FUS_TEXT_001_ACTION_BODY = [
  "import adsk.core",
  "import adsk.fusion",
  "units = design.unitsManager",
  "params = design.userParameters",
  "plate_length = params.add('plate_length', adsk.core.ValueInput.createByString('120 mm'), 'mm', 'Finished length')",
  "plate_width = params.add('plate_width', adsk.core.ValueInput.createByString('80 mm'), 'mm', 'Finished width')",
  "plate_thickness = params.add('plate_thickness', adsk.core.ValueInput.createByString('12 mm'), 'mm', 'Finished thickness')",
  "hole_diameter = params.add('hole_diameter', adsk.core.ValueInput.createByString('8.5 mm'), 'mm', 'Through-hole diameter')",
  "hole_edge_offset = params.add('hole_edge_offset', adsk.core.ValueInput.createByString('12 mm'), 'mm', 'Hole center edge offset')",
  "pocket_diameter = params.add('pocket_diameter', adsk.core.ValueInput.createByString('40 mm'), 'mm', 'Centered pocket diameter')",
  "pocket_depth = params.add('pocket_depth', adsk.core.ValueInput.createByString('4 mm'), 'mm', 'Pocket depth')",
  "corner_fillet = params.add('corner_fillet', adsk.core.ValueInput.createByString('4 mm'), 'mm', 'Vertical corner fillet')",
  "perimeter_chamfer = params.add('perimeter_chamfer', adsk.core.ValueInput.createByString('1.5 mm'), 'mm', 'Outer perimeter chamfer')",
  "half_l = units.evaluateExpression('plate_length / 2', 'cm')",
  "half_w = units.evaluateExpression('plate_width / 2', 'cm')",
  "offset = units.evaluateExpression('hole_edge_offset', 'cm')",
  "sketch = root.sketches.add(root.xYConstructionPlane)",
  "sketch.name = 'Plate Outline'",
  "sketch.sketchCurves.sketchLines.addTwoPointRectangle(adsk.core.Point3D.create(-half_l, -half_w, 0), adsk.core.Point3D.create(half_l, half_w, 0))",
  "base = root.features.extrudeFeatures.addSimple(sketch.profiles.item(0), adsk.core.ValueInput.createByString('plate_thickness'), adsk.fusion.FeatureOperations.NewBodyFeatureOperation)",
  "base.name = 'Plate Base'",
  "body = base.bodies.item(0)",
  "body.name = 'FUS-TEXT-001 Mounting Plate'",
  "hole_sketch = root.sketches.add(root.xYConstructionPlane)",
  "hole_sketch.name = 'Hole Centers'",
  "hole_positions = [(-half_l + offset, -half_w + offset), (half_l - offset, -half_w + offset), (half_l - offset, half_w - offset), (-half_l + offset, half_w - offset)]",
  "for index, position in enumerate(hole_positions):",
  "    point = hole_sketch.sketchPoints.add(adsk.core.Point3D.create(position[0], position[1], 0))",
  "    points = adsk.core.ObjectCollection.create()",
  "    points.add(point)",
  "    hole_input = root.features.holeFeatures.createSimpleInput(adsk.core.ValueInput.createByString('hole_diameter'))",
  "    hole_input.setPositionBySketchPoints(points)",
  "    hole_input.setAllExtent(adsk.fusion.ExtentDirections.NegativeExtentDirection)",
  "    hole = root.features.holeFeatures.add(hole_input)",
  "    hole.name = 'Through Hole %d' % (index + 1)",
  "top_z = units.evaluateExpression('plate_thickness', 'cm')",
  "plane_input = root.constructionPlanes.createInput()",
  "plane_input.setByOffset(root.xYConstructionPlane, adsk.core.ValueInput.createByString('plate_thickness'))",
  "top_plane = root.constructionPlanes.add(plane_input)",
  "top_plane.name = 'Plate Top Plane'",
  "pocket_sketch = root.sketches.add(top_plane)",
  "pocket_sketch.name = 'Centered Pocket Sketch'",
  "pocket_sketch.sketchCurves.sketchCircles.addByCenterRadius(adsk.core.Point3D.create(0, 0, 0), units.evaluateExpression('pocket_diameter / 2', 'cm'))",
  "pocket_input = root.features.extrudeFeatures.createInput(pocket_sketch.profiles.item(0), adsk.fusion.FeatureOperations.CutFeatureOperation)",
  "pocket_extent = adsk.fusion.DistanceExtentDefinition.create(adsk.core.ValueInput.createByString('pocket_depth'))",
  "pocket_input.setOneSideExtent(pocket_extent, adsk.fusion.ExtentDirections.NegativeExtentDirection)",
  "pocket = root.features.extrudeFeatures.add(pocket_input)",
  "pocket.name = 'Centered Pocket'",
  "vertical_edges = adsk.core.ObjectCollection.create()",
  "for edge in body.edges:",
  "    start = edge.startVertex.geometry",
  "    end = edge.endVertex.geometry",
  "    if abs(start.x - end.x) < 0.0001 and abs(start.y - end.y) < 0.0001 and abs(abs(start.z - end.z) - top_z) < 0.0001:",
  "        vertical_edges.add(edge)",
  "fillet_input = root.features.filletFeatures.createInput()",
  "fillet_input.addConstantRadiusEdgeSet(vertical_edges, adsk.core.ValueInput.createByString('corner_fillet'), True)",
  "fillet = root.features.filletFeatures.add(fillet_input)",
  "fillet.name = 'Vertical Corner Fillets'",
  "perimeter_edges = adsk.core.ObjectCollection.create()",
  "for edge in body.edges:",
  "    box = edge.boundingBox",
  "    on_outer_x = abs(abs(box.minPoint.x) - half_l) < 0.0001 or abs(abs(box.maxPoint.x) - half_l) < 0.0001",
  "    on_outer_y = abs(abs(box.minPoint.y) - half_w) < 0.0001 or abs(abs(box.maxPoint.y) - half_w) < 0.0001",
  "    on_end = (abs(box.minPoint.z) < 0.0001 and abs(box.maxPoint.z) < 0.0001) or (abs(box.minPoint.z - top_z) < 0.0001 and abs(box.maxPoint.z - top_z) < 0.0001)",
  "    if on_end and (on_outer_x or on_outer_y):",
  "        perimeter_edges.add(edge)",
  "chamfer_input = root.features.chamferFeatures.createInput2()",
  "chamfer_input.chamferEdgeSets.addEqualDistanceChamferEdgeSet(perimeter_edges, adsk.core.ValueInput.createByString('perimeter_chamfer'), False)",
  "chamfer = root.features.chamferFeatures.add(chamfer_input)",
  "chamfer.name = 'Outer Perimeter Chamfers'",
  "material_match = None",
  "for library in materialLibraries:",
  "    for material in library.materials:",
  "        if material.name in ('Aluminum 6061', 'Aluminum 6061-T6'):",
  "            material_match = material",
  "            break",
  "    if material_match:",
  "        break",
  "if material_match is None:",
  "    raise RuntimeError('Installed Aluminum 6061 material was not found')",
  "body.material = material_match",
  "appearance_match = None",
  "for library in materialLibraries:",
  "    for appearance in library.appearances:",
  "        if 'blue' in appearance.name.lower():",
  "            appearance_match = appearance",
  "            break",
  "    if appearance_match:",
  "        break",
  "if appearance_match is None:",
  "    raise RuntimeError('Installed blue appearance was not found')",
  "native_appearance = design.appearances.addByCopy(appearance_match, 'Chamfer Blue Anodized RGB 30 90 180')",
  "if native_appearance is None:",
  "    raise RuntimeError('Fusion could not copy the installed blue appearance')",
  "for prop in native_appearance.appearanceProperties:",
  "    try:",
  "        color = prop.value",
  "        red = color.red",
  "        green = color.green",
  "        blue = color.blue",
  "        prop.value = adsk.core.Color.create(30, 90, 180, 255)",
  "        break",
  "    except:",
  "        pass",
  "body.appearance = native_appearance",
].join("\n");

/** Deterministic image-fixture action used only by acceptance infrastructure. */
export const FUS_IMAGE_001_ACTION_BODY = [
  "import adsk.core",
  "import adsk.fusion",
  "units = design.unitsManager",
  "params = design.userParameters",
  "parameter_specs = [('base_width', '100 mm'), ('base_depth', '60 mm'), ('base_thickness', '8 mm'), ('upright_width', '100 mm'), ('upright_height_above_base', '60 mm'), ('upright_thickness', '8 mm'), ('base_hole_diameter', '7 mm'), ('base_hole_x_1', '20 mm'), ('base_hole_x_2', '80 mm'), ('base_hole_y', '20 mm'), ('upright_hole_diameter', '10 mm'), ('upright_hole_x_1', '25 mm'), ('upright_hole_x_2', '75 mm'), ('upright_hole_height', '35 mm'), ('inside_fillet_radius', '6 mm'), ('outside_chamfer_distance', '1.5 mm')]",
  "for name, expression in parameter_specs:",
  "    parameter = params.add(name, adsk.core.ValueInput.createByString(expression), 'mm', 'FUS-IMAGE-001 drawing dimension')",
  "    register_entity(parameter, 'parameter:' + name)",
  "width = units.evaluateExpression('base_width', 'cm')",
  "depth = units.evaluateExpression('base_depth', 'cm')",
  "base_sketch = root.sketches.add(root.xYConstructionPlane)",
  "base_sketch.name = 'Base Sketch'",
  "base_lines = base_sketch.sketchCurves.sketchLines.addTwoPointRectangle(adsk.core.Point3D.create(0, 0, 0), adsk.core.Point3D.create(width, depth, 0))",
  "base_width_dimension = base_sketch.sketchDimensions.addDistanceDimension(base_lines.item(0).startSketchPoint, base_lines.item(0).endSketchPoint, adsk.fusion.DimensionOrientations.HorizontalDimensionOrientation, adsk.core.Point3D.create(width / 2, -1, 0))",
  "base_width_dimension.parameter.expression = 'base_width'",
  "base_depth_dimension = base_sketch.sketchDimensions.addDistanceDimension(base_lines.item(1).startSketchPoint, base_lines.item(1).endSketchPoint, adsk.fusion.DimensionOrientations.VerticalDimensionOrientation, adsk.core.Point3D.create(width + 1, depth / 2, 0))",
  "base_depth_dimension.parameter.expression = 'base_depth'",
  "register_entity(base_sketch, 'sketch:Base Sketch@XY')",
  "base = root.features.extrudeFeatures.addSimple(base_sketch.profiles.item(0), adsk.core.ValueInput.createByString('base_thickness'), adsk.fusion.FeatureOperations.NewBodyFeatureOperation)",
  "base.name = 'Base Extrude'",
  "register_entity(base, 'feature:ExtrudeFeature:Base Extrude')",
  "body = base.bodies.item(0)",
  "body.name = 'FUS-IMAGE-001 Orange ABS Bracket'",
  "register_entity(body, 'body:FUS-IMAGE-001 Orange ABS Bracket')",
  "upright_plane_input = root.constructionPlanes.createInput()",
  "upright_plane_input.setByOffset(root.xZConstructionPlane, adsk.core.ValueInput.createByString('base_depth - upright_thickness'))",
  "upright_plane = root.constructionPlanes.add(upright_plane_input)",
  "upright_plane.name = 'Upright Front Plane'",
  "upright_sketch = root.sketches.add(upright_plane)",
  "upright_sketch.name = 'Upright Sketch'",
  "upright_height = units.evaluateExpression('base_thickness + upright_height_above_base', 'cm')",
  "upright_lines = upright_sketch.sketchCurves.sketchLines.addTwoPointRectangle(adsk.core.Point3D.create(0, 0, 0), adsk.core.Point3D.create(width, upright_height, 0))",
  "upright_width_dimension = upright_sketch.sketchDimensions.addDistanceDimension(upright_lines.item(0).startSketchPoint, upright_lines.item(0).endSketchPoint, adsk.fusion.DimensionOrientations.HorizontalDimensionOrientation, adsk.core.Point3D.create(width / 2, -1, 0))",
  "upright_width_dimension.parameter.expression = 'upright_width'",
  "upright_height_dimension = upright_sketch.sketchDimensions.addDistanceDimension(upright_lines.item(1).startSketchPoint, upright_lines.item(1).endSketchPoint, adsk.fusion.DimensionOrientations.VerticalDimensionOrientation, adsk.core.Point3D.create(width + 1, upright_height / 2, 0))",
  "upright_height_dimension.parameter.expression = 'base_thickness + upright_height_above_base'",
  "register_entity(upright_sketch, 'sketch:Upright Sketch@XZ')",
  "upright_input = root.features.extrudeFeatures.createInput(upright_sketch.profiles.item(0), adsk.fusion.FeatureOperations.JoinFeatureOperation)",
  "upright_input.setOneSideExtent(adsk.fusion.DistanceExtentDefinition.create(adsk.core.ValueInput.createByString('upright_thickness')), adsk.fusion.ExtentDirections.PositiveExtentDirection)",
  "upright = root.features.extrudeFeatures.add(upright_input)",
  "upright.name = 'Upright Extrude'",
  "register_entity(upright, 'feature:ExtrudeFeature:Upright Extrude')",
  "base_top_input = root.constructionPlanes.createInput()",
  "base_top_input.setByOffset(root.xYConstructionPlane, adsk.core.ValueInput.createByString('base_thickness'))",
  "base_top = root.constructionPlanes.add(base_top_input)",
  "base_top.name = 'Base Top Plane'",
  "for index, x_name in enumerate(['base_hole_x_1', 'base_hole_x_2']):",
  "    hole_sketch = root.sketches.add(base_top)",
  "    hole_sketch.name = 'Base Hole %d Position' % (index + 1)",
  "    point = hole_sketch.sketchPoints.add(adsk.core.Point3D.create(units.evaluateExpression(x_name, 'cm'), units.evaluateExpression('base_hole_y', 'cm'), 0))",
  "    x_dimension = hole_sketch.sketchDimensions.addDistanceDimension(hole_sketch.originPoint, point, adsk.fusion.DimensionOrientations.HorizontalDimensionOrientation, adsk.core.Point3D.create(1, -1, 0))",
  "    x_dimension.parameter.expression = x_name",
  "    y_dimension = hole_sketch.sketchDimensions.addDistanceDimension(hole_sketch.originPoint, point, adsk.fusion.DimensionOrientations.VerticalDimensionOrientation, adsk.core.Point3D.create(-1, 1, 0))",
  "    y_dimension.parameter.expression = 'base_hole_y'",
  "    register_entity(hole_sketch, 'sketch:Base Hole %d Position@XY' % (index + 1))",
  "    points = adsk.core.ObjectCollection.create()",
  "    points.add(point)",
  "    hole_input = root.features.holeFeatures.createSimpleInput(adsk.core.ValueInput.createByString('base_hole_diameter'))",
  "    hole_input.setPositionBySketchPoints(points)",
  "    hole_input.setAllExtent(adsk.fusion.ExtentDirections.PositiveExtentDirection)",
  "    try:",
  "        hole = root.features.holeFeatures.add(hole_input)",
  "    except Exception as error:",
  "        raise RuntimeError('Base hole %d failed: %s' % (index + 1, error))",
  "    hole.name = 'Base Through Hole %d' % (index + 1)",
  "    register_entity(hole, 'feature:HoleFeature:Base Through Hole %d' % (index + 1))",
  "for index, x_name in enumerate(['upright_hole_x_1', 'upright_hole_x_2']):",
  "    hole_sketch = root.sketches.add(upright_plane)",
  "    hole_sketch.name = 'Upright Hole %d Position' % (index + 1)",
  "    point = hole_sketch.sketchPoints.add(adsk.core.Point3D.create(units.evaluateExpression(x_name, 'cm'), units.evaluateExpression('base_thickness + upright_hole_height', 'cm'), 0))",
  "    x_dimension = hole_sketch.sketchDimensions.addDistanceDimension(hole_sketch.originPoint, point, adsk.fusion.DimensionOrientations.HorizontalDimensionOrientation, adsk.core.Point3D.create(1, -1, 0))",
  "    x_dimension.parameter.expression = x_name",
  "    height_dimension = hole_sketch.sketchDimensions.addDistanceDimension(hole_sketch.originPoint, point, adsk.fusion.DimensionOrientations.VerticalDimensionOrientation, adsk.core.Point3D.create(-1, 1, 0))",
  "    height_dimension.parameter.expression = 'base_thickness + upright_hole_height'",
  "    register_entity(hole_sketch, 'sketch:Upright Hole %d Position@XZ' % (index + 1))",
  "    points = adsk.core.ObjectCollection.create()",
  "    points.add(point)",
  "    hole_input = root.features.holeFeatures.createSimpleInput(adsk.core.ValueInput.createByString('upright_hole_diameter'))",
  "    hole_input.setPositionBySketchPoints(points)",
  "    hole_input.setAllExtent(adsk.fusion.ExtentDirections.NegativeExtentDirection)",
  "    try:",
  "        hole = root.features.holeFeatures.add(hole_input)",
  "    except Exception as error:",
  "        raise RuntimeError('Upright hole %d failed: %s' % (index + 1, error))",
  "    hole.name = 'Upright Through Hole %d' % (index + 1)",
  "    register_entity(hole, 'feature:HoleFeature:Upright Through Hole %d' % (index + 1))",
  "body = root.bRepBodies.item(0)",
  "junction_edges = adsk.core.ObjectCollection.create()",
  "for edge in body.edges:",
  "    box = edge.boundingBox",
  "    if abs((box.maxPoint.x - box.minPoint.x) * 10.0 - 100.0) < 0.05 and abs(box.minPoint.y * 10.0 - 52.0) < 0.05 and abs(box.minPoint.z * 10.0 - 8.0) < 0.05:",
  "        junction_edges.add(edge)",
  "fillet_input = root.features.filletFeatures.createInput()",
  "fillet_input.addConstantRadiusEdgeSet(junction_edges, adsk.core.ValueInput.createByString('inside_fillet_radius'), True)",
  "fillet = root.features.filletFeatures.add(fillet_input)",
  "fillet.name = 'Inside Junction Fillet'",
  "register_entity(fillet, 'feature:FilletFeature:Inside Junction Fillet')",
  "body = root.bRepBodies.item(0)",
  "outside_edges = adsk.core.ObjectCollection.create()",
  "for edge in body.edges:",
  "    box = edge.boundingBox",
  "    length = edge.length * 10.0",
  "    on_outside = abs(box.minPoint.y) < 0.0001 or abs(box.maxPoint.y * 10.0 - 60.0) < 0.05 or abs(box.maxPoint.z * 10.0 - 68.0) < 0.05 or abs(box.minPoint.z) < 0.0001",
  "    is_linear_exposed = edge.geometry.objectType.endswith('Line3D') and length > 10.0",
  "    if on_outside and is_linear_exposed:",
  "        outside_edges.add(edge)",
  "chamfer_input = root.features.chamferFeatures.createInput2()",
  "chamfer_input.chamferEdgeSets.addEqualDistanceChamferEdgeSet(outside_edges, adsk.core.ValueInput.createByString('outside_chamfer_distance'), False)",
  "chamfer = root.features.chamferFeatures.add(chamfer_input)",
  "chamfer.name = 'Exposed Outside Chamfers'",
  "register_entity(chamfer, 'feature:ChamferFeature:Exposed Outside Chamfers')",
  "body = root.bRepBodies.item(0)",
  "material_match = None",
  "for library in materialLibraries:",
  "    for material in library.materials:",
  "        if material.name in ('ABS Plastic', 'ABS (Generic)', 'ABS'):",
  "            material_match = material",
  "            break",
  "    if material_match:",
  "        break",
  "if material_match is None:",
  "    raise RuntimeError('Installed ABS material was not found')",
  "body.material = material_match",
  "appearance_match = None",
  "for library in materialLibraries:",
  "    for appearance in library.appearances:",
  "        if 'orange' in appearance.name.lower() or 'plastic' in appearance.name.lower():",
  "            appearance_match = appearance",
  "            break",
  "    if appearance_match:",
  "        break",
  "if appearance_match is None:",
  "    raise RuntimeError('Installed orange-compatible appearance was not found')",
  "native_appearance = design.appearances.addByCopy(appearance_match, 'Chamfer Orange RGB 240 100 20')",
  "for prop in native_appearance.appearanceProperties:",
  "    try:",
  "        color = prop.value",
  "        red = color.red",
  "        green = color.green",
  "        blue = color.blue",
  "        prop.value = adsk.core.Color.create(240, 100, 20, 255)",
  "        break",
  "    except:",
  "        pass",
  "body.appearance = native_appearance",
].join("\n");
