import type { FusionExpectedEffect } from "@chamfer/shared";

export { FUS_MM_COMPLETION_FIXTURES } from "./multimodalManual";

/** Stable acceptance contract shared only by protocol-faithful and disposable-live fixtures. */
export const FUS_TEXT_001 = {
  id: "FUS-TEXT-001",
  prompt: "FUS-TEXT-001: Create a single-solid 120 by 80 by 12 mm CNC mounting plate with four native 8.5 mm through holes 12 mm from adjacent edges, a centered native 40 mm pocket 4 mm deep, 4 mm vertical-corner fillets, 1.5 mm outer-perimeter chamfers, Aluminum 6061 engineering material, and a separate blue anodized RGB 30/90/180 appearance. Keep every dimension and feature editable in Fusion history.",
  expectedEffects: [
    { kind: "body-count", expected: 1 },
    { kind: "dimensions", expectedMm: [120, 80, 12], toleranceMm: 0.05 },
    { kind: "parameter", name: "plate_length", expectedMm: 120, toleranceMm: 0.05 },
    { kind: "parameter", name: "plate_width", expectedMm: 80, toleranceMm: 0.05 },
    { kind: "parameter", name: "plate_thickness", expectedMm: 12, toleranceMm: 0.05 },
    { kind: "parameter", name: "hole_diameter", expectedMm: 8.5, toleranceMm: 0.02 },
    { kind: "parameter", name: "hole_edge_offset", expectedMm: 12, toleranceMm: 0.05 },
    { kind: "parameter", name: "pocket_diameter", expectedMm: 40, toleranceMm: 0.05 },
    { kind: "parameter", name: "pocket_depth", expectedMm: 4, toleranceMm: 0.05 },
    { kind: "parameter", name: "corner_fillet", expectedMm: 4, toleranceMm: 0.05 },
    { kind: "parameter", name: "perimeter_chamfer", expectedMm: 1.5, toleranceMm: 0.05 },
    { kind: "holes", expected: 4, diameterMm: 8.5, edgeOffsetMm: 12, through: true, toleranceMm: 0.05 },
    { kind: "feature", featureType: "HoleFeature", minCount: 4, maxCount: 4 },
    { kind: "feature", featureType: "ExtrudeFeature", minCount: 2, maxCount: 2 },
    { kind: "pocket", name: "Centered Pocket", diameterMm: 40, depthMm: 4, centerMm: [0, 0], toleranceMm: 0.05 },
    { kind: "fillet", name: "Vertical Corner Fillets", radiusMm: 4, faceCount: 4, placement: "vertical-outer-corners", toleranceMm: 0.05 },
    { kind: "chamfer", name: "Outer Perimeter Chamfers", distanceMm: 1.5, faceCount: 16, placement: "top-bottom-outer-perimeter", toleranceMm: 0.05 },
    { kind: "material", expected: "Aluminum 6061", acceptedEquivalents: ["Aluminum 6061-T6"] },
    { kind: "appearance", targetRgb: [30, 90, 180], tolerance: 0 },
    { kind: "visual-evidence", requiredViews: ["front", "back", "left", "right", "top", "bottom", "isometric"] },
  ] satisfies FusionExpectedEffect[],
} as const;

export { FUS_IMAGE_001_ACTION_BODY, FUS_TEXT_001_ACTION_BODY } from "./action";

/** Complex industrial tracer shared by the fake-MCP and disposable-live seams. */
export const FUS_TEXT_002 = {
  id: "FUS-TEXT-002",
  prompt: "FUS-TEXT-002: Create the single-solid parametric industrial conveyor bearing support housing exactly as specified: a centered 180 x 110 x 16 mm base; a 24 mm thick, 110 mm wide upright with a semicircular R55 crown and bearing axis at X0/Z76; a named 52 mm nominal through bearing seat; a one-sided 62 x 5 mm retaining recess from datum B; four 11 mm through holes with 18 x 8 mm top counterbores at X +/-70 and Y +/-35; four 12 mm triangular gussets rising 45 mm; and a vertical native M6 x 1 threaded grease passage into the seat. Preserve named datum A/B/C construction planes, native structural fillets and all specified chamfers, one connected body, EN-GJS-500-7 ductile iron (or recorded canonical equivalent), and separate RGB 65/72/78 machine-gray appearance.",
  expectedEffects: [
    { kind: "body-count", expected: 1 },
    { kind: "dimensions", expectedMm: [180, 110, 131], toleranceMm: 0.05 },
    { kind: "named-references", names: ["Datum A - Base Bottom", "Datum B - Wall Front", "Datum C - Base Left"], referenceType: "plane", expectedOriginsMm: [[0, 0, 0], [0, -12, 0], [-90, 0, 0]], expectedNormals: [[0, 0, 1], [0, 1, 0], [1, 0, 0]], toleranceMm: 0.05 },
    { kind: "parametric-sketch", name: "Base Outline - Datum A", requiredExpressions: ["base_width", "base_depth"] },
    { kind: "parametric-sketch", name: "Upright Wall and Semicircular Crown", requiredExpressions: ["base_thickness", "bearing_axis_height - base_thickness", "crown_radius"] },
    { kind: "parametric-sketch", name: "Bearing Seat Nominal 52 mm", requiredExpressions: ["bearing_axis_height", "bearing_seat_nominal"] },
    { kind: "parametric-sketch", name: "Retaining Recess Sketch - Datum B Only", requiredExpressions: ["bearing_axis_height", "retaining_recess_diameter"] },
    { kind: "parametric-sketch", name: "Parametric Mounting Hole Centers", requiredExpressions: ["mount_x_offset", "mount_y_offset"] },
    { kind: "parametric-sketch", name: "Gusset Profile Parametric", requiredExpressions: ["base_thickness", "wall_thickness / 2", "gusset_height", "gusset_foot_offset - wall_thickness / 2"] },
    { kind: "parameter", name: "base_width", expectedMm: 180, toleranceMm: 0.05 },
    { kind: "parameter", name: "base_depth", expectedMm: 110, toleranceMm: 0.05 },
    { kind: "parameter", name: "base_thickness", expectedMm: 16, toleranceMm: 0.05 },
    { kind: "parameter", name: "wall_width", expectedMm: 110, toleranceMm: 0.05 },
    { kind: "parameter", name: "wall_thickness", expectedMm: 24, toleranceMm: 0.05 },
    { kind: "parameter", name: "bearing_axis_height", expectedMm: 76, toleranceMm: 0.02 },
    { kind: "parameter", name: "crown_radius", expectedMm: 55, toleranceMm: 0.05 },
    { kind: "parameter", name: "mount_x_offset", expectedMm: 70, toleranceMm: 0.05 },
    { kind: "parameter", name: "mount_y_offset", expectedMm: 35, toleranceMm: 0.05 },
    { kind: "parameter", name: "gusset_x_offset", expectedMm: 45, toleranceMm: 0.05 },
    { kind: "parameter", name: "gusset_foot_offset", expectedMm: 45, toleranceMm: 0.05 },
    { kind: "parameter", name: "gusset_width", expectedMm: 12, toleranceMm: 0.05 },
    { kind: "parameter", name: "bearing_seat_nominal", expectedMm: 52, toleranceMm: 0 },
    { kind: "housing-profile", name: "Upright Wall and Crown", wallWidthMm: 110, wallThicknessMm: 24, crownRadiusMm: 55, axisCenterMm: [0, 0, 76], toleranceMm: 0.05 },
    { kind: "bore", name: "Bearing Seat", nominalParameter: "bearing_seat_nominal", nominalMm: 52, minDiameterMm: 52, maxDiameterMm: 52.03, centerMm: [0, 0, 76], axis: "y", through: true, toleranceMm: 0.02 },
    { kind: "directional-recess", name: "Retaining Recess - Datum B Only", diameterMm: 62, depthMm: 5, datumName: "Datum B - Wall Front", direction: "positive", through: false, toleranceMm: 0.05 },
    { kind: "counterbored-holes", expected: 4, holeDiameterMm: 11, counterboreDiameterMm: 18, counterboreDepthMm: 8, centersMm: [[-70, -35, 16], [70, -35, 16], [70, 35, 16], [-70, 35, 16]], direction: "negative", toleranceMm: 0.05 },
    { kind: "gussets", expected: 4, widthMm: 12, heightMm: 45, centersXmm: [-45, 45], wallFacesYmm: [-12, 12], connectedBodyCount: 1, toleranceMm: 0.05 },
    { kind: "threaded-hole", name: "Grease Port M6x1", diameterMm: 6, pitchMm: 1, centerMm: [0, 0, 131], axis: "z", direction: "negative", intersectsFeature: "Bearing Seat", toleranceMm: 0.05 },
    { kind: "parameter", name: "base_corner_fillet", expectedMm: 5, toleranceMm: 0.05 },
    { kind: "fillet", name: "Base Corner Fillets", radiusMm: 5, faceCount: 4, placement: "base-vertical-outer-corners", toleranceMm: 0.05 },
    { kind: "feature", featureType: "FilletFeature", name: "Structural Fillets", minCount: 1, maxCount: 1 },
    { kind: "feature", featureType: "FilletFeature", name: "Gusset Root Fillets", minCount: 1, maxCount: 1 },
    { kind: "feature", featureType: "ChamferFeature", name: "Bearing Mouth Chamfers", minCount: 1, maxCount: 1 },
    { kind: "feature", featureType: "ChamferFeature", name: "Grease Port Entry Chamfer", minCount: 1, maxCount: 1 },
    { kind: "feature", featureType: "ChamferFeature", name: "Base Perimeter Chamfer", minCount: 1, maxCount: 1 },
    { kind: "edge-treatment", treatment: "fillet", name: "Structural Fillets", sizeMm: 6, minFaceCount: 2, placement: "wall-roots", toleranceMm: 0.05 },
    { kind: "edge-treatment", treatment: "fillet", name: "Gusset Root Fillets", sizeMm: 6, minFaceCount: 4, placement: "gusset-roots", toleranceMm: 0.05 },
    { kind: "edge-treatment", treatment: "chamfer", name: "Bearing Mouth Chamfers", sizeMm: 1, minFaceCount: 2, placement: "bearing-mouths", toleranceMm: 0.05 },
    { kind: "edge-treatment", treatment: "chamfer", name: "Grease Port Entry Chamfer", sizeMm: 0.5, minFaceCount: 1, placement: "grease-entry", toleranceMm: 0.05 },
    { kind: "edge-treatment", treatment: "chamfer", name: "Base Perimeter Chamfer", sizeMm: 2, minFaceCount: 4, placement: "base-top-outer-perimeter", toleranceMm: 0.05 },
    { kind: "material", expected: "EN-GJS-500-7", acceptedEquivalents: ["Ductile Iron", "Ductile Cast Iron", "Iron, Ductile"], requireLibraryProvenance: true },
    { kind: "appearance", targetRgb: [65, 72, 78], tolerance: 0 },
    { kind: "visual-evidence", requiredViews: ["front", "back", "left", "right", "top", "bottom", "isometric", "section"] },
  ] satisfies FusionExpectedEffect[],
} as const;

export { FUS_TEXT_002_ACTION_BODY } from "./industrialAction";

export const FUS_IMAGE_001 = {
  id: "FUS-IMAGE-001",
  prompt: "Use the attached FUS-IMAGE-001 dimensioned drawing as the authoritative geometry reference and model one editable parametric Fusion bracket in millimeters. Assign ABS plastic, apply orange RGB 240/100/20, preserve the native 6 mm inside fillet and 1.5 mm exposed-edge chamfer, and complete only after current visual verification matches the drawing.",
  reference: {
    fileName: "FUS-IMAGE-001-reference.png",
    sha256: "80bc33c78bcd890486f7b48ed1845491422384d6445428a9575e74f6ec4ab86c",
    views: ["front", "top", "right"] as const,
  },
  expectedEffects: [
    { kind: "body-count", expected: 1 },
    { kind: "dimensions", expectedMm: [100, 60, 68], toleranceMm: 0.05 },
    { kind: "parameter", name: "base_width", expectedMm: 100, toleranceMm: 0.05 },
    { kind: "parameter", name: "base_depth", expectedMm: 60, toleranceMm: 0.05 },
    { kind: "parameter", name: "base_thickness", expectedMm: 8, toleranceMm: 0.05 },
    { kind: "parameter", name: "upright_width", expectedMm: 100, toleranceMm: 0.05 },
    { kind: "parameter", name: "upright_height_above_base", expectedMm: 60, toleranceMm: 0.05 },
    { kind: "parameter", name: "upright_thickness", expectedMm: 8, toleranceMm: 0.05 },
    { kind: "parameter", name: "base_hole_diameter", expectedMm: 7, toleranceMm: 0.05 },
    { kind: "parameter", name: "upright_hole_diameter", expectedMm: 10, toleranceMm: 0.05 },
    { kind: "parameter", name: "inside_fillet_radius", expectedMm: 6, toleranceMm: 0.05 },
    { kind: "parameter", name: "outside_chamfer_distance", expectedMm: 1.5, toleranceMm: 0.05 },
    { kind: "hole-pattern", expected: 2, diameterMm: 7, through: true,
      centersMm: [[20, 20, 8], [80, 20, 8]], normal: [0, 0, 1], toleranceMm: 0.05 },
    { kind: "hole-pattern", expected: 2, diameterMm: 10, through: true,
      centersMm: [[25, 52, 43], [75, 52, 43]], normal: [0, 1, 0], toleranceMm: 0.05 },
    { kind: "feature", featureType: "ExtrudeFeature", name: "Base Extrude", minCount: 1, maxCount: 1 },
    { kind: "feature", featureType: "ExtrudeFeature", name: "Upright Extrude", minCount: 1, maxCount: 1 },
    { kind: "feature", featureType: "HoleFeature", minCount: 4, maxCount: 4 },
    { kind: "feature", featureType: "FilletFeature", name: "Inside Junction Fillet", minCount: 1, maxCount: 1, expectedSizeMm: 6, toleranceMm: 0.05 },
    { kind: "feature", featureType: "ChamferFeature", name: "Exposed Outside Chamfers", minCount: 1, maxCount: 1, expectedSizeMm: 1.5, toleranceMm: 0.05 },
    { kind: "material", expected: "ABS Plastic", acceptedEquivalents: ["ABS (Generic)", "ABS"] },
    { kind: "appearance", targetRgb: [240, 100, 20], tolerance: 0 },
    { kind: "visual-evidence", requiredViews: ["front", "back", "left", "right", "top", "bottom", "isometric"] },
  ] satisfies FusionExpectedEffect[],
} as const;
