/** Deterministic reviewed action body for the disposable FUS-TEXT-002 fixture. */
export const FUS_TEXT_002_ACTION_BODY = [
  "import adsk.core",
  "import adsk.fusion",
  "units = design.unitsManager",
  "params = design.userParameters",
  "def add_param(name, expression, comment):",
  "    return params.add(name, adsk.core.ValueInput.createByString(expression), 'mm', comment)",
  "base_width = add_param('base_width', '180 mm', 'Datum C to opposite end')",
  "base_depth = add_param('base_depth', '110 mm', 'Centered base depth')",
  "base_thickness = add_param('base_thickness', '16 mm', 'Datum A to base top')",
  "wall_thickness = add_param('wall_thickness', '24 mm', 'Upright thickness about datum B')",
  "bearing_axis_height = add_param('bearing_axis_height', '76 mm', 'Bearing axis above datum A')",
  "crown_radius = add_param('crown_radius', '55 mm', 'Semicircular crown radius')",
  "wall_width = add_param('wall_width', '2 * crown_radius', 'Upright width driven by semicircular crown')",
  "bearing_seat_nominal = add_param('bearing_seat_nominal', '52 mm', 'Nominal H7 bearing seat')",
  "retaining_recess_diameter = add_param('retaining_recess_diameter', '62 mm', 'Front retaining recess diameter')",
  "retaining_recess_depth = add_param('retaining_recess_depth', '5 mm', 'Depth from datum B only')",
  "mount_hole_diameter = add_param('mount_hole_diameter', '11 mm', 'Base mounting through hole')",
  "counterbore_diameter = add_param('counterbore_diameter', '18 mm', 'Socket head counterbore')",
  "counterbore_depth = add_param('counterbore_depth', '8 mm', 'Counterbore depth from base top')",
  "gusset_width = add_param('gusset_width', '12 mm', 'Gusset width along X')",
  "gusset_height = add_param('gusset_height', '45 mm', 'Gusset rise above base')",
  "mount_x_offset = add_param('mount_x_offset', '70 mm', 'Mounting-hole X offset from datum center')",
  "mount_y_offset = add_param('mount_y_offset', '35 mm', 'Mounting-hole Y offset from datum center')",
  "gusset_x_offset = add_param('gusset_x_offset', '45 mm', 'Gusset center X offset')",
  "gusset_foot_offset = add_param('gusset_foot_offset', '45 mm', 'Gusset foot Y offset')",
  "grease_port_diameter = add_param('grease_port_diameter', '6 mm', 'M6 grease port nominal')",
  "grease_port_pitch = add_param('grease_port_pitch', '1 mm', 'M6 thread pitch')",
  "structural_fillet = add_param('structural_fillet', '6 mm', 'Wall and gusset root fillet')",
  "base_corner_fillet = add_param('base_corner_fillet', '5 mm', 'Four vertical base corner edges')",
  "bearing_chamfer = add_param('bearing_chamfer', '1 mm', 'Bearing mouth chamfer')",
  "grease_chamfer = add_param('grease_chamfer', '0.5 mm', 'Grease entry chamfer')",
  "base_chamfer = add_param('base_chamfer', '2 mm', 'Exposed base perimeter chamfer')",
  "half_base_width = units.evaluateExpression('base_width / 2', 'cm')",
  "half_base_depth = units.evaluateExpression('base_depth / 2', 'cm')",
  "base_top_z = units.evaluateExpression('base_thickness', 'cm')",
  "half_wall_width = units.evaluateExpression('wall_width / 2', 'cm')",
  "half_wall_thickness = units.evaluateExpression('wall_thickness / 2', 'cm')",
  "axis_z = units.evaluateExpression('bearing_axis_height', 'cm')",
  "crown_top_z = units.evaluateExpression('bearing_axis_height + crown_radius', 'cm')",
  "mount_x = units.evaluateExpression('mount_x_offset', 'cm')",
  "mount_y = units.evaluateExpression('mount_y_offset', 'cm')",
  "gusset_x = units.evaluateExpression('gusset_x_offset', 'cm')",
  "gusset_foot = units.evaluateExpression('gusset_foot_offset', 'cm')",
  "datum_a_input = root.constructionPlanes.createInput()",
  "datum_a_input.setByOffset(root.xYConstructionPlane, adsk.core.ValueInput.createByString('0 mm'))",
  "datum_a = root.constructionPlanes.add(datum_a_input)",
  "datum_a.name = 'Datum A - Base Bottom'",
  "datum_b_input = root.constructionPlanes.createInput()",
  "datum_b_input.setByOffset(root.xZConstructionPlane, adsk.core.ValueInput.createByString('-wall_thickness / 2'))",
  "datum_b = root.constructionPlanes.add(datum_b_input)",
  "datum_b.name = 'Datum B - Wall Front'",
  "datum_c_input = root.constructionPlanes.createInput()",
  "datum_c_input.setByOffset(root.yZConstructionPlane, adsk.core.ValueInput.createByString('-base_width / 2'))",
  "datum_c = root.constructionPlanes.add(datum_c_input)",
  "datum_c.name = 'Datum C - Base Left'",
  "base_top_plane_input = root.constructionPlanes.createInput()",
  "base_top_plane_input.setByOffset(root.xYConstructionPlane, adsk.core.ValueInput.createByString('base_thickness'))",
  "base_top_plane = root.constructionPlanes.add(base_top_plane_input)",
  "base_sketch = root.sketches.add(root.xYConstructionPlane)",
  "base_sketch.name = 'Base Outline - Datum A'",
  "base_outline = base_sketch.sketchCurves.sketchLines.addCenterPointRectangle(adsk.core.Point3D.create(0, 0, 0), adsk.core.Point3D.create(half_base_width, half_base_depth, 0))",
  "base_horizontal = None",
  "base_vertical = None",
  "for base_line_index in range(base_outline.count):",
  "    base_line = base_outline.item(base_line_index)",
  "    if abs(base_line.endSketchPoint.geometry.x - base_line.startSketchPoint.geometry.x) > abs(base_line.endSketchPoint.geometry.y - base_line.startSketchPoint.geometry.y): base_horizontal = base_line",
  "    if abs(base_line.endSketchPoint.geometry.y - base_line.startSketchPoint.geometry.y) > abs(base_line.endSketchPoint.geometry.x - base_line.startSketchPoint.geometry.x): base_vertical = base_line",
  "if base_horizontal is None or base_vertical is None: raise RuntimeError('parametric base rectangle dimensions were not found')",
  "base_sketch.sketchDimensions.addDistanceDimension(base_horizontal.startSketchPoint, base_horizontal.endSketchPoint, adsk.fusion.DimensionOrientations.AlignedDimensionOrientation, adsk.core.Point3D.create(0, -half_base_depth - 1, 0)).parameter.expression = 'base_width'",
  "base_sketch.sketchDimensions.addDistanceDimension(base_vertical.startSketchPoint, base_vertical.endSketchPoint, adsk.fusion.DimensionOrientations.AlignedDimensionOrientation, adsk.core.Point3D.create(half_base_width + 1, 0, 0)).parameter.expression = 'base_depth'",
  "base = root.features.extrudeFeatures.addSimple(base_sketch.profiles.item(0), adsk.core.ValueInput.createByString('base_thickness'), adsk.fusion.FeatureOperations.NewBodyFeatureOperation)",
  "base.name = 'One Solid Base'",
  "body = base.bodies.item(0)",
  "body.name = 'FUS-TEXT-002 Industrial Bearing Housing'",
  "base_corner_edges = adsk.core.ObjectCollection.create()",
  "for edge in body.edges:",
  "    box = edge.boundingBox",
  "    if box.minPoint.z <= 0.001 and box.maxPoint.z >= base_top_z - 0.001 and abs(abs((box.minPoint.x + box.maxPoint.x) / 2) - half_base_width) <= 0.01 and abs(abs((box.minPoint.y + box.maxPoint.y) / 2) - half_base_depth) <= 0.01: base_corner_edges.add(edge)",
  "base_fillet_input = root.features.filletFeatures.createInput()",
  "base_fillet_input.addConstantRadiusEdgeSet(base_corner_edges, adsk.core.ValueInput.createByString('base_corner_fillet'), True)",
  "base_corner_fillets = root.features.filletFeatures.add(base_fillet_input)",
  "base_corner_fillets.name = 'Base Corner Fillets'",
  "wall_sketch = root.sketches.add(root.xZConstructionPlane)",
  "wall_sketch.name = 'Upright Wall and Semicircular Crown'",
  "wall_lines = wall_sketch.sketchCurves.sketchLines",
  "wall_bottom = wall_lines.addByTwoPoints(adsk.core.Point3D.create(-half_wall_width, -base_top_z, 0), adsk.core.Point3D.create(half_wall_width, -base_top_z, 0))",
  "wall_right = wall_lines.addByTwoPoints(wall_bottom.endSketchPoint, adsk.core.Point3D.create(half_wall_width, -axis_z, 0))",
  "crown_arc = wall_sketch.sketchCurves.sketchArcs.addByThreePoints(wall_right.endSketchPoint.geometry, adsk.core.Point3D.create(0, -crown_top_z, 0), adsk.core.Point3D.create(-half_wall_width, -axis_z, 0))",
  "wall_left = wall_lines.addByTwoPoints(crown_arc.endSketchPoint, wall_bottom.startSketchPoint)",
  "wall_sketch.geometricConstraints.addVertical(wall_sketch.originPoint, crown_arc.centerSketchPoint)",
  "wall_sketch.sketchDimensions.addDistanceDimension(wall_sketch.originPoint, wall_bottom.startSketchPoint, adsk.fusion.DimensionOrientations.VerticalDimensionOrientation, adsk.core.Point3D.create(-half_wall_width - 1, -base_top_z / 2, 0)).parameter.expression = 'base_thickness'",
  "wall_sketch.sketchDimensions.addDistanceDimension(wall_right.startSketchPoint, wall_right.endSketchPoint, adsk.fusion.DimensionOrientations.AlignedDimensionOrientation, adsk.core.Point3D.create(half_wall_width + 1, -(axis_z + base_top_z) / 2, 0)).parameter.expression = 'bearing_axis_height - base_thickness'",
  "wall_sketch.sketchDimensions.addRadialDimension(crown_arc, adsk.core.Point3D.create(half_wall_width / 2, -crown_top_z, 0)).parameter.expression = 'crown_radius'",
  "wall_input = root.features.extrudeFeatures.createInput(wall_sketch.profiles.item(0), adsk.fusion.FeatureOperations.JoinFeatureOperation)",
  "wall_input.setSymmetricExtent(adsk.core.ValueInput.createByString('wall_thickness'), True)",
  "wall = root.features.extrudeFeatures.add(wall_input)",
  "wall.name = 'Upright Wall and Crown'",
  "body = root.bRepBodies.item(0)",
  "wall_root_edges = adsk.core.ObjectCollection.create()",
  "for edge in body.edges:",
  "    box = edge.boundingBox",
  "    if abs(box.minPoint.z - base_top_z) <= 0.001 and abs(box.maxPoint.z - base_top_z) <= 0.001 and abs(abs((box.minPoint.y + box.maxPoint.y) / 2) - half_wall_thickness) <= 0.01 and box.maxPoint.x - box.minPoint.x >= half_wall_width: wall_root_edges.add(edge)",
  "if wall_root_edges.count == 0: raise RuntimeError('no accessible wall-to-base structural edges were found')",
  "wall_fillet_input = root.features.filletFeatures.createInput()",
  "wall_fillet_input.addConstantRadiusEdgeSet(wall_root_edges, adsk.core.ValueInput.createByString('structural_fillet'), False)",
  "fillets = root.features.filletFeatures.add(wall_fillet_input)",
  "fillets.name = 'Structural Fillets'",
  "seat_sketch = root.sketches.add(root.xZConstructionPlane)",
  "seat_sketch.name = 'Bearing Seat Nominal 52 mm'",
  "seat_circle = seat_sketch.sketchCurves.sketchCircles.addByCenterRadius(adsk.core.Point3D.create(0, -axis_z, 0), units.evaluateExpression('bearing_seat_nominal / 2', 'cm'))",
  "seat_sketch.geometricConstraints.addVertical(seat_sketch.originPoint, seat_circle.centerSketchPoint)",
  "seat_sketch.sketchDimensions.addDistanceDimension(seat_sketch.originPoint, seat_circle.centerSketchPoint, adsk.fusion.DimensionOrientations.VerticalDimensionOrientation, adsk.core.Point3D.create(1, -axis_z / 2, 0)).parameter.expression = 'bearing_axis_height'",
  "seat_sketch.sketchDimensions.addDiameterDimension(seat_circle, adsk.core.Point3D.create(half_wall_width / 2, -axis_z, 0)).parameter.expression = 'bearing_seat_nominal'",
  "seat_input = root.features.extrudeFeatures.createInput(seat_sketch.profiles.item(0), adsk.fusion.FeatureOperations.CutFeatureOperation)",
  "seat_input.setSymmetricExtent(adsk.core.ValueInput.createByString('40 mm'), True)",
  "seat = root.features.extrudeFeatures.add(seat_input)",
  "seat.name = 'Bearing Seat'",
  "recess_sketch = root.sketches.add(datum_b)",
  "recess_sketch.name = 'Retaining Recess Sketch - Datum B Only'",
  "recess_circle = recess_sketch.sketchCurves.sketchCircles.addByCenterRadius(adsk.core.Point3D.create(0, -axis_z, 0), units.evaluateExpression('retaining_recess_diameter / 2', 'cm'))",
  "recess_sketch.geometricConstraints.addVertical(recess_sketch.originPoint, recess_circle.centerSketchPoint)",
  "recess_sketch.sketchDimensions.addDistanceDimension(recess_sketch.originPoint, recess_circle.centerSketchPoint, adsk.fusion.DimensionOrientations.VerticalDimensionOrientation, adsk.core.Point3D.create(1, -axis_z / 2, 0)).parameter.expression = 'bearing_axis_height'",
  "recess_sketch.sketchDimensions.addDiameterDimension(recess_circle, adsk.core.Point3D.create(half_wall_width / 2, -axis_z, 0)).parameter.expression = 'retaining_recess_diameter'",
  "recess_input = root.features.extrudeFeatures.createInput(recess_sketch.profiles.item(0), adsk.fusion.FeatureOperations.CutFeatureOperation)",
  "recess_input.setOneSideExtent(adsk.fusion.DistanceExtentDefinition.create(adsk.core.ValueInput.createByString('retaining_recess_depth')), adsk.fusion.ExtentDirections.PositiveExtentDirection)",
  "recess = root.features.extrudeFeatures.add(recess_input)",
  "recess.name = 'Retaining Recess - Datum B Only'",
  "mount_sketch = root.sketches.add(base_top_plane)",
  "mount_sketch.name = 'Parametric Mounting Hole Centers'",
  "for x, y in [(-mount_x, -mount_y), (mount_x, -mount_y), (mount_x, mount_y), (-mount_x, mount_y)]:",
  "    body = root.bRepBodies.item(0)",
  "    mount_point = mount_sketch.sketchPoints.add(adsk.core.Point3D.create(x, y, 0))",
  "    mount_sketch.sketchDimensions.addDistanceDimension(mount_sketch.originPoint, mount_point, adsk.fusion.DimensionOrientations.HorizontalDimensionOrientation, adsk.core.Point3D.create(x / 2, y - 1, 0)).parameter.expression = 'mount_x_offset'",
  "    mount_sketch.sketchDimensions.addDistanceDimension(mount_sketch.originPoint, mount_point, adsk.fusion.DimensionOrientations.VerticalDimensionOrientation, adsk.core.Point3D.create(x + 1, y / 2, 0)).parameter.expression = 'mount_y_offset'",
  "    mount_points = adsk.core.ObjectCollection.create()",
  "    mount_points.add(mount_point)",
  "    hole_input = root.features.holeFeatures.createCounterboreInput(adsk.core.ValueInput.createByString('mount_hole_diameter'), adsk.core.ValueInput.createByString('counterbore_diameter'), adsk.core.ValueInput.createByString('counterbore_depth'))",
  "    hole_input.setPositionBySketchPoints(mount_points)",
  "    hole_input.participantBodies = [body]",
  "    hole_input.setAllExtent(adsk.fusion.ExtentDirections.NegativeExtentDirection)",
  "    try: mounting_holes = root.features.holeFeatures.add(hole_input)",
  "    except Exception as error: raise RuntimeError('mounting counterbore failed at %s,%s: %s' % (x, y, error))",
  "    mounting_holes.name = 'Counterbored Mounting Holes'",
  "for gusset_plane_sign in [-1, 1]:",
  "    gusset_plane_input = root.constructionPlanes.createInput()",
  "    gusset_plane_input.setByOffset(root.yZConstructionPlane, adsk.core.ValueInput.createByString(('-' if gusset_plane_sign < 0 else '') + 'gusset_x_offset'))",
  "    gusset_plane = root.constructionPlanes.add(gusset_plane_input)",
  "    gusset_plane.name = 'Gusset Plane X %s' % ('-' if gusset_plane_sign < 0 else '+')",
  "    gusset_sketch = root.sketches.add(gusset_plane)",
  "    gusset_sketch.name = 'Gusset Profile Parametric'",
  "    gusset_lines = gusset_sketch.sketchCurves.sketchLines",
  "    for side in [-1, 1]:",
  "        y_wall = side * half_wall_thickness",
  "        y_foot = side * gusset_foot",
  "        gusset_base = gusset_lines.addByTwoPoints(adsk.core.Point3D.create(-base_top_z, y_wall, 0), adsk.core.Point3D.create(-base_top_z, y_foot, 0))",
  "        gusset_slope = gusset_lines.addByTwoPoints(gusset_base.endSketchPoint, adsk.core.Point3D.create(-(base_top_z + units.evaluateExpression('gusset_height', 'cm')), y_wall, 0))",
  "        gusset_wall = gusset_lines.addByTwoPoints(gusset_slope.endSketchPoint, gusset_base.startSketchPoint)",
  "        gusset_sketch.sketchDimensions.addDistanceDimension(gusset_wall.startSketchPoint, gusset_wall.endSketchPoint, adsk.fusion.DimensionOrientations.AlignedDimensionOrientation, adsk.core.Point3D.create(-(base_top_z + units.evaluateExpression('gusset_height / 2', 'cm')), y_wall - side, 0)).parameter.expression = 'gusset_height'",
  "        gusset_sketch.sketchDimensions.addDistanceDimension(gusset_base.startSketchPoint, gusset_base.endSketchPoint, adsk.fusion.DimensionOrientations.AlignedDimensionOrientation, adsk.core.Point3D.create(-base_top_z + side, (y_wall + y_foot) / 2, 0)).parameter.expression = 'gusset_foot_offset - wall_thickness / 2'",
  "        gusset_sketch.sketchDimensions.addDistanceDimension(gusset_sketch.originPoint, gusset_base.startSketchPoint, adsk.fusion.DimensionOrientations.HorizontalDimensionOrientation, adsk.core.Point3D.create(-base_top_z / 2, y_wall - side, 0)).parameter.expression = 'base_thickness'",
  "        gusset_sketch.sketchDimensions.addDistanceDimension(gusset_sketch.originPoint, gusset_base.startSketchPoint, adsk.fusion.DimensionOrientations.VerticalDimensionOrientation, adsk.core.Point3D.create(-base_top_z + side, y_wall / 2, 0)).parameter.expression = 'wall_thickness / 2'",
  "    for profile_index in range(gusset_sketch.profiles.count):",
  "        gusset_input = root.features.extrudeFeatures.createInput(gusset_sketch.profiles.item(profile_index), adsk.fusion.FeatureOperations.JoinFeatureOperation)",
  "        gusset_input.setSymmetricExtent(adsk.core.ValueInput.createByString('gusset_width'), True)",
  "        gusset = root.features.extrudeFeatures.add(gusset_input)",
  "        gusset.name = 'Gusset %d' % (root.features.extrudeFeatures.count)",
  "        body = root.bRepBodies.item(0)",
  "gusset_root_edges = adsk.core.ObjectCollection.create()",
  "for edge in body.edges:",
  "    box = edge.boundingBox",
  "    is_wall_root = abs(abs((box.minPoint.y + box.maxPoint.y) / 2) - half_wall_thickness) <= 0.001 and box.maxPoint.z - box.minPoint.z >= units.evaluateExpression('gusset_height - structural_fillet - 0.1 mm', 'cm')",
  "    is_gusset_side = abs(abs((box.minPoint.x + box.maxPoint.x) / 2) - gusset_x) <= units.evaluateExpression('gusset_width / 2', 'cm') + 0.01",
  "    if is_wall_root and is_gusset_side: gusset_root_edges.add(edge)",
  "if gusset_root_edges.count == 0: raise RuntimeError('no accessible gusset-root edges were found')",
  "gusset_fillet_input = root.features.filletFeatures.createInput()",
  "gusset_fillet_input.addConstantRadiusEdgeSet(gusset_root_edges, adsk.core.ValueInput.createByString('structural_fillet'), False)",
  "gusset_root_fillets = root.features.filletFeatures.add(gusset_fillet_input)",
  "gusset_root_fillets.name = 'Gusset Root Fillets'",
  "crown_plane_input = root.constructionPlanes.createInput()",
  "crown_plane_input.setByOffset(root.xYConstructionPlane, adsk.core.ValueInput.createByString('bearing_axis_height + crown_radius'))",
  "crown_plane = root.constructionPlanes.add(crown_plane_input)",
  "thread_query = root.features.threadFeatures.threadDataQuery",
  "thread_found, thread_designation, thread_class = thread_query.recommendThreadData(units.evaluateExpression('grease_port_diameter', 'cm'), True, 'ISO Metric profile')",
  "if not thread_found or thread_designation != 'M6x1': raise RuntimeError('installed ISO thread table did not resolve M6x1')",
  "thread_info = root.features.threadFeatures.createThreadInfo(True, 'ISO Metric profile', thread_designation, thread_class)",
  "grease_input = root.features.holeFeatures.createSimpleInput(adsk.core.ValueInput.createByString('grease_port_diameter'))",
  "grease_input.setToTappedHole(thread_info)",
  "grease_input.isModeled = False",
  "grease_input.isFullLength = True",
  "grease_input.setPositionByPoint(crown_plane, adsk.core.Point3D.create(0, 0, crown_top_z))",
  "grease_input.participantBodies = [body]",
  "grease_input.isDefaultDirection = True",
  "grease_input.setDistanceExtent(adsk.core.ValueInput.createByString('70 mm'))",
  "try: grease_port = root.features.holeFeatures.add(grease_input)",
  "except Exception as error: raise RuntimeError('grease port failed: %s' % error)",
  "grease_port.name = 'Grease Port M6x1'",
  "body = root.bRepBodies.item(0)",
  "grease_thread = grease_port.thread",
  "grease_thread.name = 'Grease Port M6x1 Native Thread'",
  "bearing_edges = adsk.core.ObjectCollection.create()",
  "grease_edges = adsk.core.ObjectCollection.create()",
  "base_edges = adsk.core.ObjectCollection.create()",
  "for grease_side_index in range(grease_port.sideFaces.count):",
  "    grease_side = grease_port.sideFaces.item(grease_side_index)",
  "    for grease_edge in grease_side.edges:",
  "        if grease_edge.boundingBox.maxPoint.z >= 13.0: grease_edges.add(grease_edge)",
  "for edge in body.edges:",
  "    box = edge.boundingBox",
  "    circle = adsk.core.Circle3D.cast(edge.geometry)",
  "    if circle and abs(circle.radius - 2.6) <= 0.001 and abs(circle.normal.y) >= 0.999: bearing_edges.add(edge)",
  "    reaches_base_perimeter = max(abs(box.minPoint.x), abs(box.maxPoint.x)) >= half_base_width - units.evaluateExpression('base_corner_fillet + 0.1 mm', 'cm') or max(abs(box.minPoint.y), abs(box.maxPoint.y)) >= half_base_depth - units.evaluateExpression('base_corner_fillet + 0.1 mm', 'cm')",
  "    if box.minPoint.z >= base_top_z - 0.001 and box.maxPoint.z <= base_top_z + 0.001 and reaches_base_perimeter: base_edges.add(edge)",
  "def add_chamfer(edges, expression, name):",
  "    if edges.count == 0: raise RuntimeError('%s has no selected edges' % name)",
  "    chamfer_input = root.features.chamferFeatures.createInput2()",
  "    chamfer_input.chamferEdgeSets.addEqualDistanceChamferEdgeSet(edges, adsk.core.ValueInput.createByString(expression), False)",
  "    try: result = root.features.chamferFeatures.add(chamfer_input)",
  "    except Exception as error: raise RuntimeError('%s failed on %s edges: %s' % (name, edges.count, error))",
  "    result.name = name",
  "    return result",
  "bearing_mouth_chamfers = add_chamfer(bearing_edges, 'bearing_chamfer', 'Bearing Mouth Chamfers')",
  "grease_port_chamfer = add_chamfer(grease_edges, 'grease_chamfer', 'Grease Port Entry Chamfer')",
  "base_perimeter_chamfer = add_chamfer(base_edges, 'base_chamfer', 'Base Perimeter Chamfer')",
  "section_input = design.analyses.sectionAnalyses.createInput(root.xZConstructionPlane, 0)",
  "bearing_section = design.analyses.sectionAnalyses.add(section_input)",
  "bearing_section.name = 'FUS-TEXT-002 Bearing Section'",
  "bearing_section.isHatchShown = True",
  "bearing_section.isLightBulbOn = False",
  "material_match = None",
  "for library in materialLibraries:",
  "    for material in library.materials:",
  "        if material.name in ('EN-GJS-500-7', 'Ductile Iron', 'Ductile Cast Iron', 'Iron, Ductile'):",
  "            material_match = material",
  "            break",
  "    if material_match: break",
  "if material_match is None: raise RuntimeError('Installed ductile-iron material was not found')",
  "body.material = material_match",
  "appearance_source = None",
  "for library in materialLibraries:",
  "    for appearance in library.appearances:",
  "        if 'gray' in appearance.name.lower() or 'grey' in appearance.name.lower():",
  "            appearance_source = appearance",
  "            break",
  "    if appearance_source: break",
  "if appearance_source is None: raise RuntimeError('Installed gray appearance was not found')",
  "machine_gray = design.appearances.addByCopy(appearance_source, 'Machine Gray RGB 65 72 78')",
  "for appearance_property in machine_gray.appearanceProperties:",
  "    try:",
  "        existing_color = appearance_property.value",
  "        red = existing_color.red",
  "        appearance_property.value = adsk.core.Color.create(65, 72, 78, 255)",
  "        break",
  "    except:",
  "        pass",
  "body.appearance = machine_gray",
].join("\n");
