// Generates .wrangler.dev.jsonc (gitignored) for `wrangler dev`: identical to
// wrangler.jsonc except the container image builds from the local Dockerfile
// instead of the pinned registry reference, so dev always runs this branch's
// container code. The committed config must stay a registry reference because
// Workers Builds has no Docker (see the containers block comment).
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const packageDir = dirname(dirname(fileURLToPath(import.meta.url)));
const source = readFileSync(join(packageDir, "wrangler.jsonc"), "utf8");

const registryImage = /"image":\s*"registry\.cloudflare\.com\/[^"]+"/;
if (!registryImage.test(source)) {
  console.error("dev-config: wrangler.jsonc no longer pins a registry image; update this script's rewrite");
  process.exit(1);
}
const generated = source.replace(registryImage, '"image": "./container/Dockerfile"');

writeFileSync(
  join(packageDir, ".wrangler.dev.jsonc"),
  `// Generated by scripts/dev-config.mjs - do not edit, edit wrangler.jsonc.\n${generated}`,
);
console.log("dev config generated: .wrangler.dev.jsonc (container image builds from ./container/Dockerfile)");
